logging:
  path: /var/logs/
  file: Calculator.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongodb.calculator.com
      port: 27018
      username: calculator
      password:
        - letMeIn
      database: calculatordb

logging:
  level:
    root: WARN
    org:
      springframework:
        secuirty: WARNING
